version: '3'
services:
  python3:
    env_file:
      - envfile.env
    restart: always
    container_name: python-docker
    build:
        context: .
        dockerfile: Dockerfile
    working_dir: '/home/vscode/work'
    tty: true
    volumes:
      - .:/home/vscode/work